// SPDX-License-Identifier: GPL-3.0-or-later

#include "reboot/mlir_emitter.h"

#include <fmt/format.h>

#include <algorithm>
#include <stdexcept>
#include <vector>

namespace reboot {
namespace {

std::string float_literal(double value) {
	return fmt::format("{:.6e}", value);
}

// dense<c> when every slot carries the same constant, dense<[...]> otherwise.
std::string dense_attr(const SlotConstant &constant) {
	if (constant.splat)
		return fmt::format("dense<{}>", float_literal(constant.values.front()));
	std::string body;
	for (size_t i = 0; i < constant.values.size(); ++i)
		body += fmt::format("{}{}", i ? ", " : "",
							float_literal(constant.values[i]));
	return fmt::format("dense<[{}]>", body);
}

class Emitter {
   public:
	Emitter(const LoweredStep &step, const EmitOptions &options)
		: step_(step),
		  options_(options),
		  chain_(generate_modulus_chain(options.params)) {}

	std::string run() {
		emit_prologue();
		emit_function();
		return out_;
	}

   private:
	void line(const std::string &text) { out_ += text + "\n"; }

	void emit_prologue() {
		const CkksParams &p = options_.params;
		const int n = p.ring_dim();

		line(
			"// Generated by reboot_emit - ReBoot training step for "
			"KeyMemRT-Compiler.");
		line(fmt::format(
			"// Layout {} over {} slots; feed this to keymemrt-opt.",
			step_.graph.layout().str(), step_.graph.layout().slots()));
		line("");

		// One alias per RNS prime, then the chain, the rings and the types.
		for (uint64_t q : chain_.q)
			line(fmt::format("!Z{}_i64 = !mod_arith.int<{} : i64>", q, q));
		line("");

		std::string rns;
		for (size_t i = 0; i < chain_.q.size(); ++i)
			rns += fmt::format("{}!Z{}_i64", i ? ", " : "", chain_.q[i]);
		std::string elements;
		for (size_t i = 0; i < chain_.q.size(); ++i)
			elements += fmt::format("{}{} : i64", i ? ", " : "", chain_.q[i]);

		line(fmt::format("!rns_L{} = !rns.rns<{}>", chain_.q.size() - 1, rns));
		line(
			fmt::format("#ring_f64 = #polynomial.ring<coefficientType = f64, "
						"polynomialModulus = <1 + x**{}>>",
						n));
		line(fmt::format(
			"#ring_rns = #polynomial.ring<coefficientType = !rns_L{}, "
			"polynomialModulus = <1 + x**{}>>",
			chain_.q.size() - 1, n));
		line(fmt::format(
			"#encoding = #lwe.inverse_canonical_encoding<scaling_factor = {}>",
			p.log_scale));
		line("#key = #lwe.key<>");
		line(fmt::format(
			"#modulus_chain = #lwe.modulus_chain<elements = <{}>, current = "
			"{}>",
			elements, chain_.q.size() - 1));
		line(
			"#plaintext_space = #lwe.plaintext_space<ring = #ring_f64, "
			"encoding = #encoding>");
		line(
			"#ciphertext_space = #lwe.ciphertext_space<ring = #ring_rns, "
			"encryption_type = mix>");
		line(
			"#ciphertext_space_d3 = #lwe.ciphertext_space<ring = #ring_rns, "
			"encryption_type = mix, size = 3>");
		line("!pt = !lwe.lwe_plaintext<plaintext_space = #plaintext_space>");
		line(
			"!ct = !lwe.lwe_ciphertext<plaintext_space = #plaintext_space, "
			"ciphertext_space = #ciphertext_space, key = #key, modulus_chain "
			"= #modulus_chain>");
		line(
			"!ct_d3 = !lwe.lwe_ciphertext<plaintext_space = "
			"#plaintext_space, ciphertext_space = #ciphertext_space_d3, key = "
			"#key, modulus_chain = #modulus_chain>");
		line("");
		line(fmt::format("module attributes {{ckks.schemeParam = {}}} {{",
						 scheme_param_attr(p, chain_)));
	}

	// One tensor in, one tensor out.
	//
	// keymemrt-translate emits C++ only for single-result functions
	// (OpenFhePkeEmitter: "Only functions with a single return type are
	// supported"), and a training step has to hand back every updated weight,
	// every velocity and the predictions.  A `tensor<Nx!ct>` converts to
	// `std::vector<CiphertextT>`, so bundling both sides keeps the generated
	// signature translatable *and* independent of the network shape - the host
	// runner fills a vector in the documented order instead of being rebuilt
	// whenever a layer width changes.
	void emit_function() {
		const SlotGraph &g = step_.graph;
		names_.assign(g.size(), "");

		const size_t num_args = step_.arguments.size();
		const size_t num_results = step_.results.size();
		const std::string arg_type = fmt::format("tensor<{}x!ct>", num_args);
		const std::string result_type =
			fmt::format("tensor<{}x!ct>", num_results);

		// The argument order is part of the ABI, so it travels with the module.
		std::string names;
		for (size_t i = 0; i < num_args; ++i)
			names += fmt::format("{}\"{}\"", i ? ", " : "",
								 step_.argument_names[i]);
		std::string result_names;
		for (size_t i = 0; i < num_results; ++i)
			result_names += fmt::format("{}\"{}\"", i ? ", " : "",
										step_.result_names[i]);

		line(fmt::format(
			"  func.func @{}(%args: {} {{reboot.argument_names = [{}]}}) -> {} "
			"attributes {{reboot.result_names = [{}]}} {{",
			options_.function_name, arg_type, names, result_type,
			result_names));

		const size_t max_index = std::max(num_args, num_results);
		for (size_t i = 0; i < max_index; ++i)
			line(fmt::format("    %idx{} = arith.constant {} : index", i, i));

		for (size_t i = 0; i < num_args; ++i) {
			const SlotId id = step_.arguments[i];
			names_[id] = fmt::format("%arg{}", i);
			line(fmt::format("    {} = tensor.extract %args[%idx{}] : {}  // {}",
							 names_[id], i, arg_type,
							 step_.argument_names[i]));
		}

		emit_constants();

		for (const SlotValue &v : g.values()) {
			if (v.op == SlotOp::kArgument) continue;
			emit_value(v);
		}

		line(fmt::format("    %res_init = tensor.empty() : {}", result_type));
		std::string accumulator = "%res_init";
		for (size_t i = 0; i < num_results; ++i) {
			const std::string next = fmt::format("%res_{}", i);
			line(fmt::format(
				"    {} = tensor.insert {} into {}[%idx{}] : {}  // {}", next,
				names_[step_.results[i]], accumulator, i, result_type,
				step_.result_names[i]));
			accumulator = next;
		}
		line(fmt::format("    return {} : {}", accumulator, result_type));
		line("  }");
		line("}");
	}

	void emit_constants() {
		const SlotGraph &g = step_.graph;
		const int slots = g.layout().slots();
		constant_names_.clear();
		for (size_t i = 0; i < g.constants().size(); ++i) {
			const SlotConstant &c = g.constants()[i];
			const std::string cst = fmt::format("%cst_{}", i);
			const std::string pt = fmt::format("%pt_{}", i);
			line(fmt::format("    // {}", c.name));
			line(fmt::format("    {} = arith.constant {} : tensor<{}xf64>", cst,
							 dense_attr(c), slots));
			line(fmt::format(
				"    {} = lwe.rlwe_encode {} {{encoding = #encoding, ring = "
				"#ring_f64}} : tensor<{}xf64> -> !pt",
				pt, cst, slots));
			constant_names_.push_back(pt);
		}
	}

	std::string fresh(SlotId id) {
		const std::string name = fmt::format("%{}", next_ssa_++);
		names_[id] = name;
		return name;
	}

	std::string comment(const SlotValue &v) const {
		if (!options_.annotate || v.name.empty()) return "";
		return fmt::format("  // {}", v.name);
	}

	void emit_value(const SlotValue &v) {
		const std::string &a = v.inputs.empty() ? empty_ : names_[v.inputs[0]];
		switch (v.op) {
			case SlotOp::kArgument:
				break;

			case SlotOp::kAdd:
				line(fmt::format(
					"    {} = ckks.add {}, {} : (!ct, !ct) -> !ct{}",
					fresh(v.id), a, names_[v.inputs[1]], comment(v)));
				break;

			case SlotOp::kSub:
				line(fmt::format(
					"    {} = ckks.sub {}, {} : (!ct, !ct) -> !ct{}",
					fresh(v.id), a, names_[v.inputs[1]], comment(v)));
				break;

			case SlotOp::kMul: {
				// A ciphertext product leaves the canonical key basis; relinearise
				// straight back so every value in the module has the same type.
				const std::string wide = fmt::format("%{}", next_ssa_++);
				line(fmt::format(
					"    {} = ckks.mul {}, {} : (!ct, !ct) -> !ct_d3", wide, a,
					names_[v.inputs[1]]));
				line(fmt::format(
					"    {} = ckks.relinearize {} {{from_basis = array<i32: 0, "
					"1, 2>, to_basis = array<i32: 0, 1>}} : (!ct_d3) -> !ct{}",
					fresh(v.id), wide, comment(v)));
				break;
			}

			case SlotOp::kMulPlain:
				line(fmt::format(
					"    {} = ckks.mul_plain {}, {} : (!ct, !pt) -> !ct{}",
					fresh(v.id), a, constant_names_.at(v.constant),
					comment(v)));
				break;

			case SlotOp::kAddPlain:
				line(fmt::format(
					"    {} = ckks.add_plain {}, {} : (!ct, !pt) -> !ct{}",
					fresh(v.id), a, constant_names_.at(v.constant),
					comment(v)));
				break;

			case SlotOp::kMulScalar:
				line(fmt::format(
					"    {} = ckks.mul_scalar {} {{scalar = {} : f64}} : !ct "
					"-> "
					"!ct{}",
					fresh(v.id), a, float_literal(v.scalar), comment(v)));
				break;

			case SlotOp::kRotate:
				// The index has to be visible here: this is what becomes
				// kmrt.load_key / openfhe.rot / kmrt.clear_key downstream.
				line(fmt::format(
					"    {} = ckks.rotate {} {{static_shift = {} : i64}} : "
					"!ct{}",
					fresh(v.id), a, v.rotation, comment(v)));
				break;

			case SlotOp::kBootstrap:
				line(fmt::format("    {} = ckks.bootstrap {} : !ct -> !ct{}",
								 fresh(v.id), a, comment(v)));
				break;
		}
	}

	const LoweredStep &step_;
	const EmitOptions &options_;
	ModulusChain chain_;
	std::string out_;
	std::vector<std::string> names_;
	std::vector<std::string> constant_names_;
	std::string empty_;
	int next_ssa_ = 0;
};

}  // namespace

std::string emit_mlir(const LoweredStep &step, const EmitOptions &options) {
	if (step.results.empty())
		throw std::invalid_argument("nothing to emit: the step has no results");
	Emitter emitter(step, options);
	return emitter.run();
}

}  // namespace reboot
